FROM golang:1.19
RUN mkdir backend
COPY . backend
WORKDIR backend
RUN go get ./...
#CMD ["DB_HOST=localhost DB_USER=postgres DB_PASSWORD=mysecretpassword DB_NAME=postgres DB_PORT=5432 ALLOWED_ORIGINS=localhost", "go run main.go"]
CMD DB_HOST=172.17.0.2 DB_USER=postgres DB_PASSWORD=mysecretpassword DB_NAME=postgres DB_PORT=5432 ALLOWED_ORIGINS=* go run main.go
#CMD DB_HOST=Divyanshus-MacBook-Air.local DB_USER=postgres DB_PASSWORD=mysecretpassword DB_NAME=postgres DB_PORT=5432 ALLOWED_ORIGINS=localhost go run main.go
