name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    # - name: Docker login
    #   uses: docker/login-action@v3.0.0
    #   with:
    #     registry: dssshahu
    #     username: dssshahu
    #     password: ${{ secrets.DOCKER_HUB_LOGIN }}
    - name: Build and push Docker images
      uses: docker/build-push-action@v5.0.0
      with:
        # Path to the Dockerfile
        file: ./frontend
        push: False
    
            
          
                
            
            
              
